$('.owl-carousel').owlCarousel({
    loop:true,
    margin:5,
    nav:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:2,
            margin:-70
        },
        30:{
            items:2,
            margin:-1000
        },
        400:{
            items:2,
            margin:-100
        },
        600:{
            items:3,
            margin:10
        },
       
        700:{
            items:3,
            margin:-150
        },
        800:{
            items:4,
            margin:-150
        },
        1100:{
            items:6,
            margin:100
        },
        1150:{
            items:6,
            margin:100
        },
        1200:{
            items:6,
            margin:160
        },
        1300:{
            items:6,
            margin:-90
        },
        1500:{
            items:6,
            margin:-100
        },
        1700:{
            items:6,
            margin:-700
        },
        1800:{
            items:6,
            margin:-700
        },
        1950:{
            items:7,
            margin:900
        },
        2000:{
            items:7,
            margin:-600
        },
        2300:{
            items:7,
            margin:-900
        },
        2500:{
            items:7,
            margin:-1000
        }
    }
})